[project]
name = "tddkatas"
version = "0.1.0"
description = "TDD Manifesto exercises"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
]

[tools.pytest.pytest_ini]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-v --tb=short --strict-markers"
